const {
  FORMULARIO_MEDICO_TOTAL_MENTE,
  FORMULARIO_MEDICO_TOTAL_FISICO,
  FORMULARIO_MEDICO_1_MENTE,
  FORMULARIO_MEDICO_1_FISICO,
  FORMULARIO_MEDICO_ADN_MENTE,
  FORMULARIO_MEDICO_ADN_FISICO,
  FORMULARIO_MEDICO_RESPUESTA_A_MEDICAMENTOS,
  FORMULARIO_MEDICO_FILTRO_ADN_MENTE,
  FORMULARIO_MEDICO_FILTRO_ADN_FISICO,
  FORMULARIO_PACIENTE_SINTOMAS_MEDICOS,
  FORMULARIO_PACIENTE_SALUD_PHQ9,
  FORMULARIO_PACIENTE_ESTRES_PERCIBIDO,
  FORMULARIO_PACIENTE_TRANSTORNO_DE_ANSIEDAD_GENERALIZADA
} = process.env;

const FORMS = {
  FORMULARIO_MEDICO_RESPUESTA_A_MEDICAMENTOS,
  FORMULARIO_MEDICO_FILTRO_ADN_MENTE,
  FORMULARIO_MEDICO_ADN_MENTE,
  FORMULARIO_MEDICO_FILTRO_ADN_FISICO,
  FORMULARIO_MEDICO_ADN_FISICO,
  FORMULARIO_PACIENTE_SINTOMAS_MEDICOS,
  FORMULARIO_PACIENTE_SALUD_PHQ9,
  FORMULARIO_PACIENTE_ESTRES_PERCIBIDO,
  FORMULARIO_PACIENTE_TRANSTORNO_DE_ANSIEDAD_GENERALIZADA
};

const COMPUTED_FORMS = {
  ANEXO_MENTAL: 'ANEXO_MENTAL',
  COCIENTE_DE_BIENESTAR_PONDERADO_CON_ADN: 'COCIENTE_DE_BIENESTAR_PONDERADO_CON_ADN'
};

module.exports = {
  FORMS,
  COMPUTED_FORMS
};
