const pacienteSintomasEn = require('./pacienteSintomas__en');

test('pacienteSintomasEn', () => {
  const FORM_CONFIG = {
    maxValue: 5
  };
  const mocks = [
    {
      results: {
        Headaches: 3,
        Faintness: 1,
        Dizziness: 0,
        Insomnia: 2,
        'Irregular or skipped heartbeat': 0,
        'Rapid or pounding heartbeat': 0,
        'Chest pain': 0,
        'Fatigue, sluggishness': 1,
        'Apathy, Lethargy': 1,
        Hyperactivity: 2,
        Restlessness: 0,
        'Jet lag': 0,
        'Watery or itchy eyes': 2,
        'Swollen, reddened or sticky eyelids': 1,
        'Bags or dark circles under eyes': 2,
        'Blurred or tunnel vision (Does not include near of far-sightedness)': 0,
        'Chest Congestion': 0,
        'Asthma / Bronchitis': 0,
        'Shortness of breath': 0,
        'Poor Memory': 1,
        'Confusion, poor comprehension': 0,
        'Poor concentration': 0,
        'Poor physical coordination': 0,
        'Difficulty in making decisions': 0,
        'Stuttering or stammering': 0,
        'Slurred speech': 0,
        'Learning disabilities': 0,
        'Itchy ears': 0,
        'Earaches, ear infections': 1,
        'Drainage from ear': 0,
        'Ringing in ears, hearing loss': 0,
        'Nausea, vomiting': 0,
        Diarrhea: 2,
        Constipation: 3,
        'Bloated feeling': 0,
        'Belching, passing gas': 1,
        Heartburn: 2,
        'Intestinal / stomach pain': 1,
        'Mood swings': 2,
        'Anxiety, fear, nervousness': 1,
        'Anger, irritability, aggressiveness': 2,
        Depression: 1,
        'Stuffy nose': 2,
        'Sinus problems': 2,
        'Hey Fever': 2,
        'Sneezing attacks': 2,
        'Excessive mucus formation': 2,
        'Pain or aches in joints': 1,
        Arthrítis: 1,
        'Stiffness or limitation of movement': 1,
        'Pain or aches in muscles': 1,
        'Feeling of weakness or tiredness': 1,
        'Chronic coughing': 0,
        'Gagging, frequent need to clear throat': 0,
        'Sore throat, hoarseness, loss of voice': 0,
        'Swollen or discolored tongue, gums, lips': 0,
        'Canker sores': 2,
        'Binge eating/drinking': 2,
        'Craving certain foods': 2,
        'Excessive weight': 2,
        'Compulsive eating': 2,
        'Water retention': 2,
        Underweight: 0,
        Acne: 0,
        'Hives, rashes, dry skin': 1,
        'Hair loss': 2,
        'Flushing, hot flashes': 1,
        'Excessive sweating': 0,
        'Frequent illness': 1,
        'Frequent or urgent orination': 0,
        'Genital itch or discharge': 0,
        'Bone-ache': 0,
        'How do you relate to your family?': 4,
        'How do you relate to your partner?': 5,
        'How do you relate to your friends and colleagues at work': 4,
        'How do you evaluate your hobbies in life ?': 5,
        'How do you evaluate your relationships around hobbies or other spaces different than work?': 5,
        'How satisfying is your work for you?': 5
      },

      expected: '0.79'
    },
    {
      results: {
        'Headaches': 1,
        'Faintness': 4,
        'Dizziness': 3,
        'Insomnia': 0,
        'Irregular or skipped heartbeat': 0,
        'Rapid or pounding heartbeat': 4,
        'Chest pain': 0,
        'Fatigue, sluggishness': 0,
        'Apathy, Lethargy': 4,
        'Hyperactivity': 1,
        'Restlessness': 2,
        'Jet lag': 1,
        'Watery or itchy eyes': 3,
        'Swollen, reddened or sticky eyelids': 2,
        'Bags or dark circles under eyes': 2,
        'Blurred or tunnel vision (Does not include near of far-sightedness)': 2,
        'Chest Congestion': 1,
        'Asthma / Bronchitis': 0,
        'Shortness of breath': 4,
        'Poor Memory': 1,
        'Confusion, poor comprehension': 1,
        'Poor concentration': 2,
        'Poor physical coordination': 0,
        'Difficulty in making decisions': 1,
        'Stuttering or stammering': 3,
        'Slurred speech': 4,
        'Learning disabilities': 3,
        'Itchy ears': 0,
        'Earaches, ear infections': 4,
        'Drainage from ear': 1,
        'Ringing in ears, hearing loss': 3,
        'Nausea, vomiting': 1,
        'Diarrhea': 1,
        'Constipation': 2,
        'Bloated feeling': 2,
        'Belching, passing gas': 4,
        'Heartburn': 3,
        'Intestinal / stomach pain': 0,
        'Mood swings': 2,
        'Anxiety, fear, nervousness': 1,
        'Anger, irritability, aggressiveness': 0,
        'Depression': 4,
        'Stuffy nose': 3,
        'Sinus problems': 1,
        'Hey Fever': 0,
        'Sneezing attacks': 2,
        'Excessive mucus formation': 1,
        'Pain or aches in joints': 1,
        'Arthrítis': 1,
        'Stiffness or limitation of movement': 1,
        'Pain or aches in muscles': 1,
        'Feeling of weakness or tiredness': 2,
        'Chronic coughing': 3,
        'Gagging, frequent need to clear throat': 2,
        'Sore throat, hoarseness, loss of voice': 0,
        'Swollen or discolored tongue, gums, lips': 1,
        'Canker sores': 4,
        'Binge eating/drinking': 2,
        'Craving certain foods': 0,
        'Excessive weight': 3,
        'Compulsive eating': 2,
        'Water retention': 0,
        'Underweight': 1,
        'Acne': 1,
        'Hives, rashes, dry skin': 1,
        'Hair loss': 1,
        'Flushing, hot flashes': 4,
        'Excessive sweating': 0,
        'Frequent illness': 4,
        'Frequent or urgent orination': 2,
        'Genital itch or discharge': 3,
        'Bone-ache': 0,
        'How do you relate to your family?': 4,
        'How do you relate to your partner?': 3,
        'How do you relate to your friends and colleagues at work': 3,
        'How do you evaluate your hobbies in life ?': 1,
        'How do you evaluate your relationships around hobbies or other spaces different than work?': 3,
        'How satisfying is your work for you?': 4
      },
      expected: '0.57'
    }
  ];

  mocks.forEach((mock) => {
    expect(pacienteSintomasEn({}, FORM_CONFIG, mock.results)['wellnessQuotient']).toBe(mock.expected);
  });
});
